import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]
[env]
TERM = "xterm-256color"

[window]
startup_mode = "SimpleFullscreen"
decorations = "None"
opacity = 0.9

[font]
#	normal = { family = "/Users/anita/.local/share/fonts/FiraCode Nerd Font Regular.ttf" }
#normal.family = "FiraCode NF"
#size = 15.0


[colors.primary]
background = "#181818"


[bell]
color = "#003300"
duration = 0

[selection]
save_to_clipboard = true
