import=[
   # "~/.config/alacritty/themes/themes/coolnight.toml"
     "~/.config/alacritty/themes/themes/solarized_osaka.toml",
 #   "~/.config/alacritty/themes/themes/cyber_punk_neon.toml"
]

[env]
TERM="xterm-256color"

[window]
startup_mode="Windowed"
opacity=0.9
option_as_alt="Both"
padding={x=15,y=20}  


[font]
normal={family="FiraCode Nerd Font",style="Regular"}
bold={family="FiraCode Nerd Font",style="Bold"}
italic={family="FiraCode Nerd Font",style="Italic"}
bold_italic={family="FiraCode Nerd Font",style="Bold Italic"}
#offset = { x = 1, y = 2 }   # Offset is extra space around each character
#glyph_offset = { x = 0, y = 0 }  
#builtin_box_drawing = true
size=14.0

[selection]
save_to_clipboard=true
